apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpudoc-frontend
  namespace: helpudoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helpudoc-frontend
  template:
    metadata:
      labels:
        app: helpudoc-frontend
    spec:
      containers:
        - name: frontend
          image: helpudoc-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helpudoc-frontend
  namespace: helpudoc
spec:
  type: LoadBalancer
  selector:
    app: helpudoc-frontend
  ports:
    - port: 80
      targetPort: 80
